// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	hello "go_zero_demo/http/internal/handler/hello"
	user "go_zero_demo/http/internal/handler/user"
	"go_zero_demo/http/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/from/:name",
				Handler: hello.FromHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/add",
				Handler: hello.AddHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/del",
				Handler: hello.DelHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/list",
				Handler: hello.ListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/RpcList",
				Handler: hello.RpcListHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/http/hello"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/add",
				Handler: user.AddUserHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/user"),
	)
}
