// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	hello "http/internal/handler/hello"
	user "http/internal/handler/user"
	"http/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/from/:name",
				Handler: hello.HelloHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/hello"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/add",
				Handler: user.AddUserHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/user"),
	)
}
