version: '3'

######## 项目依赖的环境，启动项目之前要先启动此环境 #######
######## The environment that the project depends on, starting this environment before starting the project #######

services:
  # mysql
  ser_brl_mysql:
    image: mysql/mysql-server:8.0.28
    container_name: brl_mysql
    environment:
      - TZ=Asia/Shanghai
      - LANG=C.UTF-8
      - MYSQL_DATABASE=demo
      - MYSQL_USER=demo
      - MYSQL_PASSWORD=demo
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 33061:3306
    volumes:
      # 数据挂载 - Data mounting
      - ./docker_data/mysql/data:/var/lib/mysql
      # 日志
    command:
      # 将mysql8.0默认密码策略 修改为 原先 策略 (mysql8.0对其默认策略做了更改 会导致密码无法匹配) 
      # Modify the Mysql 8.0 default password strategy to the original strategy (MySQL8.0 to change its default strategy will cause the password to be unable to match)
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
    privileged: true
    restart: on-failure

  # phpmyadmin
  ser_brl_phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: brl_phpmyadmin
    restart: on-failure
    environment:
      - PMA_ARBITRARY=0
      - MYSQL_USER=demo
      - MYSQL_PASSWORD=demo
      - MYSQL_ROOT_PASSWORD=root
      - PMA_HOST=ser_brl_mysql
    ports:
      - 33062:80
    depends_on:
      - ser_brl_mysql 
      
  # redis容器 - Redis container
  ser_brl_redis:
    image: redis:6.2.5
    container_name: brl_redis
    ports:
      - 36371:6379
    environment:
      # 时区上海 - Time zone Shanghai (Change if needed)
      TZ: Asia/Shanghai
    volumes:
      # 数据文件 - data files
      - ./docker_data/redis/data:/data:rw
    command: "redis-server --requirepass G62m50oigInC30sf  --appendonly yes"
    privileged: true
    restart: on-failure

  # etcd容器
  ser_brl_etcd:
    image: quay.io/coreos/etcd:v3.5.0
    container_name: brl_etcd
    command: /usr/local/bin/etcd --name node1 --initial-advertise-peer-urls http://brl_etcd:2380 --listen-peer-urls http://0.0.0.0:2380 --advertise-client-urls http://brl_etcd:2379 --listen-client-urls http://0.0.0.0:2379 --initial-cluster node1=http://brl_etcd:2380
    ports:
      - 2379:2379
      - 2380:2380
    volumes:
      - ./docker_data/etcd:/etcd-data

  # etcdkeeper容器
  ser_brl_etcdkeeper:
    image: deltaprojects/etcdkeeper
    container_name: brl_etcdkeeper
    ports:
      - 23799:8080
    environment:
      - ETCD_SERVER=http://brl_etcd:2379
    depends_on:
      - ser_brl_etcd 

  #prometheus监控 — Prometheus for monitoring
  ser_brl_prometheus:
    image: prom/prometheus:v2.28.1
    container_name: brl_prometheus
    environment:
      # 时区上海 - Time zone Shanghai (Change if needed)
      TZ: Asia/Shanghai
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./docker_data/prometheus/data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    restart: on-failure
    user: root
    ports:
      - 9090:9090

  #jaeger链路追踪 — Jaeger for tracing
  ser_brl_jaeger:
    image: jaegertracing/all-in-one:1.5
    container_name: brl_jaeger
    restart: on-failure
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
    environment:
#      - SPAN_STORAGE_TYPE=elasticsearch
#      - ES_SERVER_URLS=http://elasticsearch:9200
      - LOG_LEVEL=debug
  ser_meilisearch:
    image: getmeili/meilisearch:v1.5
    container_name: brl_meilisearch
    restart: on-failure
    ports:
      - "7700:7700"
    environment:
      - MEILI_MASTER_KEY=RWzzZQj1UWqKQLmOaP7HleQIWaRAc8HA-LjpBNfJCAo
    volumes:
      - ./docker_data/meili_data:/meili_data