// Code generated by goctl. DO NOT EDIT.
// Source: hello.proto

package server

import (
	"context"

	"go_zero_demo/rpc/hello/hello"
	"go_zero_demo/rpc/hello/internal/logic"
	"go_zero_demo/rpc/hello/internal/svc"
)

type HelloServer struct {
	svcCtx *svc.ServiceContext
	hello.UnimplementedHelloServer
}

func NewHelloServer(svcCtx *svc.ServiceContext) *HelloServer {
	return &HelloServer{
		svcCtx: svcCtx,
	}
}

func (s *HelloServer) Ping(ctx context.Context, in *hello.Request) (*hello.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}

func (s *HelloServer) UserList(ctx context.Context, in *hello.UserListReq) (*hello.UserListResp, error) {
	l := logic.NewUserListLogic(ctx, s.svcCtx)
	return l.UserList(in)
}
