// Code generated by goctl. DO NOT EDIT.
package types

type PageReq struct {
	Page     int `json:"page,default=1"`
	PageSize int `json:"pageSize,default=10"`
}

type FromReq struct {
	Name string `path:"name,options=you|me"`
}

type FromRes struct {
	Message string `json:"message"`
}

type AddHelloReq struct {
	Name string `json:"name"`
}

type AddHelloRes struct {
	Id int64 `json:"id"`
}

type DelHelloReq struct {
	Id int `json:"id"`
}

type DelHelloRes struct {
}

type HelloListReq struct {
	PageReq
}

type HelloListItem struct {
	Id         int64  `json:"id"`
	Name       string `json:"name"`
	CreateTime int    `gorm:"column:createTime"`
}

type HelloListResp struct {
	List  []*HelloListItem `json:"list"`
	Total int64            `json:"total"`
}

type HelloRpcListResp struct {
	List  []*HelloListItem `json:"list"`
	Total int64            `json:"total"`
}

type AddUserReq struct {
	Name string `path:"name,options=you|me"`
}

type AddUserRes struct {
	Message string `json:"message"`
}
