// Code generated by goctl. DO NOT EDIT.
package types

type HelloHandlerReq struct {
	Name string `path:"name,options=you|me"`
}

type HelloHandlerRes struct {
	Message string `json:"message"`
}

type AddUserReq struct {
	Name string `path:"name,options=you|me"`
}

type AddUserRes struct {
	Message string `json:"message"`
}
